version: '3.6'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./environment/local.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.5.2.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    volumes:
      - ./hasura/migrations/:/hasura-migrations/
      - ./hasura/metadata/:/hasura-metadata/
    env_file:
      - ./environment/local.env
    restart: always

  sample: 
    build: 
      dockerfile: ./sample.Dockerfile
      context: .
      target: development
    command: npm run start sample
    ports:
      - '3000:8080'
    depends_on:
      - 'postgres'
    volumes:
      - ./:/nanotrust/
    env_file:
      - ./environment/local.env
    restart: always
volumes:
  db_data:
